#+TITLE: fcitx-remote-for-windows11

This is Windows11 version of project [[https://github.com/cute-jumper/fcitx-remote-for-windows][fcitx-remote-for-windows]].

Changes compared to fcitx-remote-for-windows:
- fcitx-remote-for-windows dose not work on windows11(in my configuration at least), this project fixed it;
    - Cause: The function ~BOOL isEngLayout()~ dose not work properly on Windows11, it always return true. see source code for more information;
- fcitx-remote-for-windows toggle keyboard-layout by simulating hotkey, while this project toggle keyboard-layout by PostMessage() to Windows11.
    - So there's no need to care about =ALT+SHIFT= or =WIN+SPACE= stuff.

* Build Instructions
** Build by Yourself
   This project is built from Visual Studio 2022. Import the project
   into Visual Studio and build the executable file.

** Use pre-built releases
   You can download the pre-built releases at [github release] page of this project.

* Emacs Setup
  Make sure =fcitx-remote= is in your =PATH= and =exec-path=. If not, use the following code in your =init.el=:
  #+BEGIN_SRC elisp
    (let ((fcitx-path "C:/path/to/fcitx-remote"))
      (setenv "PATH" (concat fcitx-path ";" (getenv "PATH")))
      (add-to-list 'exec-path fcitx-path))
  #+END_SRC

* MISC
  During devolopement, I found:
  1. fcitx-remote.exe dosen't work on CMD(call exe directly in CMD), but it works fine on powershell and emacs.
     I guess maybe there's no message handler on CMD. So maybe the hotkey method is more general(hotkey method works fine on CMD/powershell/emacs).
     I leave a hotkey version implementation located in ./fcitx-remote/fcitx-remote-by-hotkey.cpp, you can use this version if you like.
  2. I have test the time consumption of calling fcitx-remote.exe, it tooks 15ms on average in powershell, and 80ms on average in emacs.
     Maybe calling exe from emacs have extra cost. Anyway, The current degree of lag is acceptable to me.
  3. If you want to be more smoother, then I'm afraid you can't use the call-exe method.
     This requires modifying the source code of [[https://github.com/cute-jumper/fcitx.el][fcitx]].
     I tried to switch the input method directly by communicating between elisp and windows. The result There is no good solution;

